import type { CSSProperties } from 'react';
import type { RiskLevel } from '../types';
import { RiskBadge } from './RiskBadge';

export function RiskGauge({ score, level }: { score: number; level: RiskLevel }) {
  const safeScore = Math.max(0, Math.min(100, Number.isFinite(score) ? score : 0));
  const style = { '--score': `${safeScore}%` } as CSSProperties;

  return (
    <div className="risk-gauge-card">
      <div className="gauge" style={style} aria-label={`Risk score ${safeScore} out of 100`}>
        <div className="gauge-inner">
          <strong>{safeScore}</strong>
          <span>/100</span>
        </div>
      </div>
      <div className="gauge-copy">
        <RiskBadge level={level} />
        <p>Risk score generated by local defensive heuristics and optional reputation checks.</p>
      </div>
    </div>
  );
}
